#!/bin/sh

set -e

exec 3>&1
exec 1>&2

PAYLOAD=$(mktemp /tmp/resource-in.XXXXXX)

cat > "$PAYLOAD" <&0

TS=$(jq '.version.timestamp // empty' < "$PAYLOAD")
[ -z "$TS" ] && TS='"none"'

jq -n "{
  version: {
    timestamp: $TS
  }
}" >&3